# Generated by Django 2.2 on 2020-04-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoptype',
            old_name='type_name1',
            new_name='type_name',
        ),
        migrations.RemoveField(
            model_name='shoptype',
            name='type_name2',
        ),
    ]
