# Generated by Django 2.2.12 on 2020-05-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200419_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name']},
        ),
    ]
