# Generated by Django 2.2.12 on 2020-05-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200506_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
