# Generated by Django 2.2.12 on 2020-05-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200507_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
